import Head from "next/head";
import Link from "next/link";
import Layout from "../components/Layout";
import Hero from "../components/Hero";
import Services from "../components/Services";
import Menu from "../components/Menu";
import { client } from "../../lib/client";

export default function Home({ pizzas }) {
  // console.log(pizzas);
  return (
    <>
      <Layout>
        <Head>
          <title>Pizzalicious</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="">
          <Hero />
          <Services />
          <Menu pizzas={ pizzas } />
        </main>
      </Layout>
    </>
  );
}

export const getServerSideProps = async () => {
  const query = '*[_type == "pizza"]';
  const pizzas = await client.fetch(query);
  return {
    props: {
      pizzas,
    },
  };
};
